BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS resources(id INTEGER PRIMARY KEY, category INTEGER, image TEXT, name TEXT, rarity TEXT);
COMMIT;
